### ISSUE TITLE
Analytics tracking app

### ISSUE THREAD

**Issue by ochorocho** [Rello/analytics#155]
The repo: https://github.com/ochorocho/nextcloud-analytics-mobile

This app will allow to track data manually for type database.

Working:
  * [x] Credentials (could use the nextcloud login flow to get app password, not sure if credentials are stored in the most safe way)
  * [x] List reports
  * [x] List data (may need a pagebrowser)

ToDo:
 * [ ] Allow to add data
 * [ ] Optimize icons
 * [ ] iOS support (coz this is based on NativeScript it should be only a matter of adding a platform and adjust the view)
 * [ ] view report chart (rather low priority)

@Rello here is the current state:

https://user-images.githubusercontent.com/4623070/117725637-b2c7d580-b1e5-11eb-82a1-88cda1af4b47.mp4

**Comment by Rello** [comment]
Hello,
thank you - nice start!

So from the target definition you aim for an easy data entry, correct?
I really like that idea - I was thinking about the same already but had to prioritize it low.
I think there is a vary good usecase if you e.g. walk around the house to collect measurements.

I was thinking about using the forms app to offer a dedicated form for analytics.
second idea was a dedicated public page just for data entry.
but both did not get very far.

I also like your iOS todo

keep me updated...

**Comment by ochorocho** [comment]
> So from the target definition you aim for an easy data entry, correct?

Yes, my use case is that i have a power meter i want to track. It's located in the basement and i want to track it every now and than.

> I also like your iOS todo

I have no iPhone but a Mac with Simulator which i plan to use for testing.
Are you down for testing iOS builds? Maybe you need to build it yourself, coz i do not have a Apple Developer account.

**Comment by Rello** [comment]
Hello,
are you still approaching this?
if yes, let me know. then we can reopen the task here...

**Comment by ochorocho** [comment]
I'm currently busy with other stuff. I'll let you know once i get back to this.

**Comment by rayyume** [comment]
> I'm currently busy with other stuff. I'll let you know once i get back to this.

Hi Is it still available rn？

**Comment by ochorocho** [comment]
Sorry i did not manage to get this finished
